webauthn:
    credential_repository: App\Repository\WebauthnCredentialRepository
    user_repository: App\Repository\WebauthnUserEntityRepository
    allowed_origins:
        app: '%env(WEBAUTHN_ORIGIN)%'
    creation_profiles:
        default:
            rp:
                id: '%env(WEBAUTHN_RP_ID)%'
                name: 'BIG 4 Coffee Lounge'
    request_profiles:
        default:
            rp_id: '%env(WEBAUTHN_RP_ID)%'
    controllers:
        creation:
            faceid_register:
                options_path: /api/auth/webauthn/register/start
                result_path: /api/auth/webauthn/register/finish
                user_entity_guesser: App\Security\Webauthn\CurrentSessionUserEntityGuesser
        request:
            faceid_login:
                options_path: /api/auth/webauthn/login/start
                result_path: /api/auth/webauthn/login/finish
                success_handler: App\Security\Webauthn\AssertionLoginSuccessHandler
