ALTER TABLE dish DROP FOREIGN KEY fk_dish_menu;
ALTER TABLE dish DROP FOREIGN KEY fk_dish_menu;
ALTER TABLE dish CHANGE menu_id menu_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE base_price base_price NUMERIC(10, 0) NOT NULL, CHANGE available available TINYINT(1) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
ALTER TABLE dish ADD CONSTRAINT FK_957D8CB8CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id);
DROP INDEX fk_dish_menu ON dish;
CREATE INDEX IDX_957D8CB8CCD7E912 ON dish (menu_id);
ALTER TABLE dish ADD CONSTRAINT fk_dish_menu FOREIGN KEY (menu_id) REFERENCES menu (id) ON UPDATE CASCADE ON DELETE CASCADE;
DROP INDEX idx_ingredient_expiry_stock ON ingredient;
ALTER TABLE ingredient CHANGE quantityInStock quantityInStock NUMERIC(10, 0) NOT NULL, CHANGE unit unit VARCHAR(255) NOT NULL, CHANGE minStockLevel minStockLevel NUMERIC(10, 0) NOT NULL, CHANGE unitCost unitCost NUMERIC(10, 0) NOT NULL;
ALTER TABLE menu DROP is_active, CHANGE title title VARCHAR(255) NOT NULL, CHANGE isActive isActive TINYINT(1) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
DROP INDEX idx_wasterecord_ingredient_date ON wasterecord;
ALTER TABLE wasterecord DROP FOREIGN KEY fk_waste_ingredients;
ALTER TABLE wasterecord CHANGE quantityWasted quantityWasted NUMERIC(10, 0) NOT NULL;
DROP INDEX ingredientid ON wasterecord;
CREATE INDEX IDX_90F7A4D85B5CA8A5 ON wasterecord (ingredientId);
ALTER TABLE wasterecord ADD CONSTRAINT fk_waste_ingredients FOREIGN KEY (ingredientId) REFERENCES ingredient (id);
ALTER TABLE delivery ADD driver_latitude NUMERIC(10, 0) DEFAULT NULL, ADD driver_longitude NUMERIC(10, 0) DEFAULT NULL, ADD candidate_delivery_men LONGTEXT DEFAULT NULL, ADD candidate_index INT DEFAULT NULL, CHANGE delivery_id delivery_id INT AUTO_INCREMENT NOT NULL, CHANGE order_id order_id INT NOT NULL, CHANGE recipient_name recipient_name VARCHAR(255) DEFAULT NULL, CHANGE recipient_phone recipient_phone VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE actual_delivery_date actual_delivery_date DATETIME DEFAULT NULL, CHANGE current_latitude current_latitude NUMERIC(10, 0) DEFAULT NULL, CHANGE current_longitude current_longitude NUMERIC(10, 0) DEFAULT NULL, CHANGE delivery_notes delivery_notes LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
ALTER TABLE delivery ADD CONSTRAINT FK_3781EC10FD128646 FOREIGN KEY (delivery_man_id) REFERENCES delivery_man (delivery_man_id);
ALTER TABLE delivery ADD CONSTRAINT FK_3781EC1048CD51AF FOREIGN KEY (fleet_car_id) REFERENCES fleet_car (car_id);
DROP INDEX idx_delivery_man_id ON delivery;
CREATE INDEX IDX_3781EC10FD128646 ON delivery (delivery_man_id);
DROP INDEX idx_phone ON delivery_man;
DROP INDEX vehicle_number ON delivery_man;
DROP INDEX idx_vehicle_type ON delivery_man;
DROP INDEX idx_status ON delivery_man;
DROP INDEX email ON delivery_man;
ALTER TABLE delivery_man DROP FOREIGN KEY FK_DELIVERY_MAN_CURRENT_CAR;
ALTER TABLE delivery_man CHANGE name name VARCHAR(255) NOT NULL, CHANGE phone phone VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE vehicle_type vehicle_type VARCHAR(255) DEFAULT NULL, CHANGE vehicle_number vehicle_number VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE salary salary NUMERIC(10, 0) DEFAULT NULL, CHANGE rating rating NUMERIC(10, 0) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
DROP INDEX phone ON delivery_man;
CREATE UNIQUE INDEX UNIQ_4E0DFC7C444F97DD ON delivery_man (phone);
DROP INDEX uniq_delivery_man_license_number ON delivery_man;
CREATE UNIQUE INDEX UNIQ_4E0DFC7CEC7E7152 ON delivery_man (license_number);
DROP INDEX idx_delivery_man_current_car_id ON delivery_man;
CREATE INDEX IDX_4E0DFC7CC40F2CF1 ON delivery_man (current_car_id);
ALTER TABLE delivery_man ADD CONSTRAINT FK_DELIVERY_MAN_CURRENT_CAR FOREIGN KEY (current_car_id) REFERENCES fleet_car (car_id) ON DELETE SET NULL;
ALTER TABLE fleet_car DROP FOREIGN KEY fk_fleet_car_delivery_man;
DROP INDEX uk_fleet_delivery_man ON fleet_car;
ALTER TABLE fleet_car CHANGE make make VARCHAR(255) NOT NULL, CHANGE model model VARCHAR(255) NOT NULL, CHANGE license_plate license_plate VARCHAR(255) NOT NULL, CHANGE vehicle_type vehicle_type VARCHAR(255) NOT NULL;
ALTER TABLE food_donation_event DROP FOREIGN KEY fk_events_delivery;
DROP INDEX idx_status ON food_donation_event;
DROP INDEX idx_delivery_id ON food_donation_event;
DROP INDEX idx_event_date ON food_donation_event;
ALTER TABLE food_donation_event CHANGE delivery_id delivery_id INT DEFAULT NULL, CHANGE charity_name charity_name VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
ALTER TABLE food_donation_items DROP FOREIGN KEY fk_items_dish;
ALTER TABLE food_donation_items DROP FOREIGN KEY fk_items_event;
DROP INDEX idx_item_id ON food_donation_items;
DROP INDEX IDX_54E57C7BBABCF7FB ON food_donation_items;
ALTER TABLE orders DROP FOREIGN KEY fk_ord_client;
ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEB83297E7;
DROP INDEX client_id ON orders;
ALTER TABLE orders CHANGE Payment_method payment_method LONGTEXT DEFAULT NULL;
ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (reservation_id) ON DELETE SET NULL;
ALTER TABLE reservation DROP FOREIGN KEY fk_res_client;
DROP INDEX client_id ON reservation;
ALTER TABLE reservation CHANGE status status VARCHAR(255) NOT NULL;
ALTER TABLE restaurant_table CHANGE status status VARCHAR(255) NOT NULL;
DROP INDEX uk_email_role ON user;
ALTER TABLE user DROP full_name, DROP remember_token, DROP remember_token_expiry, CHANGE password_hash password_hash VARCHAR(255) NOT NULL, CHANGE role role VARCHAR(255) NOT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
ALTER TABLE delivery_feature ADD CONSTRAINT FK_15C9CAB812136921 FOREIGN KEY (delivery_id) REFERENCES delivery (delivery_id);
ALTER TABLE dish_ingredient DROP FOREIGN KEY fk_dish_ingredient_dish;
ALTER TABLE dish_ingredient DROP FOREIGN KEY fk_dish_ingredient_ingredient;
ALTER TABLE dish_ingredient DROP FOREIGN KEY fk_dish_ingredient_ingredient;
ALTER TABLE dish_ingredient CHANGE quantity_required quantity_required NUMERIC(10, 0) NOT NULL;
ALTER TABLE dish_ingredient ADD CONSTRAINT FK_77196056148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE;
ALTER TABLE dish_ingredient ADD CONSTRAINT FK_77196056933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE;
DROP INDEX idx_dish_ingredient_ingredient ON dish_ingredient;
CREATE INDEX IDX_77196056933FE08C ON dish_ingredient (ingredient_id);
ALTER TABLE dish_ingredient ADD CONSTRAINT fk_dish_ingredient_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE donation_event_item DROP FOREIGN KEY FK_778D4F26126F525E;
ALTER TABLE donation_event_item DROP FOREIGN KEY FK_778D4F2671F7E88B;
DROP INDEX idx_778d4f2671f7e88b ON donation_event_item;
CREATE INDEX IDX_A2E7D6FD71F7E88B ON donation_event_item (event_id);
DROP INDEX idx_778d4f26126f525e ON donation_event_item;
CREATE INDEX IDX_A2E7D6FD126F525E ON donation_event_item (item_id);
ALTER TABLE donation_event_item ADD CONSTRAINT FK_778D4F26126F525E FOREIGN KEY (item_id) REFERENCES dish (id) ON DELETE CASCADE;
ALTER TABLE donation_event_item ADD CONSTRAINT FK_778D4F2671F7E88B FOREIGN KEY (event_id) REFERENCES food_donation_event (donation_event_id) ON DELETE CASCADE;
ALTER TABLE ratings CHANGE user_id user_id BIGINT DEFAULT NULL;
ALTER TABLE ratings ADD CONSTRAINT FK_CEB607C9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL;
ALTER TABLE event_registration DROP FOREIGN KEY FK_A6A2D3B8837167D6;
ALTER TABLE event_registration CHANGE user_id user_id BIGINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)';
ALTER TABLE event_registration ADD CONSTRAINT FK_8FBBAD54A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX idx_a6a2d3b8837167d6 ON event_registration;
CREATE INDEX IDX_8FBBAD54BABCF7FB ON event_registration (donation_event_id);
DROP INDEX idx_a6a2d3b8a76ed395 ON event_registration;
CREATE INDEX IDX_8FBBAD54A76ED395 ON event_registration (user_id);
ALTER TABLE event_registration ADD CONSTRAINT FK_A6A2D3B8837167D6 FOREIGN KEY (donation_event_id) REFERENCES food_donation_event (donation_event_id) ON DELETE CASCADE;
ALTER TABLE gps_log DROP FOREIGN KEY FK_GPS_LOG_DELIVERY_MAN;
ALTER TABLE gps_log DROP FOREIGN KEY FK_GPS_LOG_CAR;
ALTER TABLE gps_log CHANGE source source VARCHAR(30) DEFAULT 'gps' NOT NULL;
DROP INDEX idx_gps_log_car_id ON gps_log;
CREATE INDEX IDX_853D94E8C3C6F69F ON gps_log (car_id);
DROP INDEX idx_gps_log_delivery_man_id ON gps_log;
CREATE INDEX IDX_853D94E8FD128646 ON gps_log (delivery_man_id);
ALTER TABLE gps_log ADD CONSTRAINT FK_GPS_LOG_DELIVERY_MAN FOREIGN KEY (delivery_man_id) REFERENCES delivery_man (delivery_man_id) ON DELETE SET NULL;
ALTER TABLE gps_log ADD CONSTRAINT FK_GPS_LOG_CAR FOREIGN KEY (car_id) REFERENCES fleet_car (car_id) ON DELETE CASCADE;
ALTER TABLE notification DROP FOREIGN KEY FK_NOTIFICATION_RECIPIENT;
DROP INDEX idx_notification_recipient_id ON notification;
CREATE INDEX IDX_BF5476CAE92F8F78 ON notification (recipient_id);
ALTER TABLE notification ADD CONSTRAINT FK_NOTIFICATION_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE password_reset_token DROP FOREIGN KEY FK_5A6E2B3EA76ED395;
ALTER TABLE password_reset_token CHANGE expires_at expires_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CHANGE created_at created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CHANGE used_at used_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)';
DROP INDEX idx_5a6e2b3ea76ed395 ON password_reset_token;
CREATE INDEX IDX_6B7BA4B6A76ED395 ON password_reset_token (user_id);
ALTER TABLE password_reset_token ADD CONSTRAINT FK_5A6E2B3EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE sustainability_metrics DROP FOREIGN KEY fk_metrics_event;
DROP INDEX idx_donation_event_id ON sustainability_metrics;
ALTER TABLE sustainability_metrics CHANGE co2_saved_kg co2_saved_kg NUMERIC(10, 0) NOT NULL, CHANGE cost_saved cost_saved NUMERIC(10, 0) DEFAULT NULL, CHANGE calculated_at calculated_at DATETIME NOT NULL;
DROP INDEX email ON user1;
ALTER TABLE user1 CHANGE name name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE role role VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL;
ALTER TABLE webauthn_credential DROP FOREIGN KEY FK_WEBAUTHN_USER_ID;
ALTER TABLE webauthn_credential CHANGE created_at created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)';
DROP INDEX idx_webauthn_user_id ON webauthn_credential;
CREATE INDEX IDX_850123F9A76ED395 ON webauthn_credential (user_id);
ALTER TABLE webauthn_credential ADD CONSTRAINT FK_WEBAUTHN_USER_ID FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL;
ALTER TABLE messenger_messages CHANGE created_at created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CHANGE available_at available_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CHANGE delivered_at delivered_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)';
