<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416234556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Legacy no-op migration kept for history compatibility. Original autogenerated SQL was incompatible with current schema.';
    }

    public function up(Schema $schema): void
    {
        // Intentionally no-op.
    }

    public function down(Schema $schema): void
    {
        // Intentionally no-op.
    }
}
