<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260417192640 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Legacy no-op migration kept for history compatibility. Original autogenerated SQL was incompatible with current schema.';
    }

    public function up(Schema $schema): void
    {
        // Intentionally no-op.
    }

    public function down(Schema $schema): void
    {
        // Intentionally no-op.
    }
}
